import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import"./global.scss"
import Navbar from "./components/Navbar";
import ReduxProvider from "./redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Italian Pizza Sydney",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${inter.className}` } >
        <ReduxProvider>
          <Navbar/>
          <div className="w-full bg-zinc-900 ">
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
